services:
  backend:
    build:
        context: .
        dockerfile: Dockerfile
    env_file:
      - .env
    ports:
        - "8000:8000"
    volumes:
        - .:/app

  mongodb:
    image: mongo:latest
    environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    env_file:
      - .env
    ports:
      - "27017:27017"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

